[package]
name = "fzf_alt"
version = "0.1.0"
authors = ["Gustavo Aguiar <gugahoa@gmail.com>"]
edition = "2018"

[dependencies]
serde_json = "*"
serde = { version = "1.0", features = ["derive"] }
serde_regex = "*"
regex = "*"
confy = "*"

[dev-dependencies]
tempfile = "*"
